// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getNullHetParamC
List getNullHetParamC(List DataList, List GroupList, int ncluster);
RcppExport SEXP phantom_getNullHetParamC(SEXP DataListSEXP, SEXP GroupListSEXP, SEXP nclusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type DataList(DataListSEXP);
    Rcpp::traits::input_parameter< List >::type GroupList(GroupListSEXP);
    Rcpp::traits::input_parameter< int >::type ncluster(nclusterSEXP);
    rcpp_result_gen = Rcpp::wrap(getNullHetParamC(DataList, GroupList, ncluster));
    return rcpp_result_gen;
END_RCPP
}
// cummaxC
arma::vec cummaxC(arma::vec x);
RcppExport SEXP phantom_cummaxC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cummaxC(x));
    return rcpp_result_gen;
END_RCPP
}
// descend2C
arma::uvec descend2C(arma::vec x, arma::vec y);
RcppExport SEXP phantom_descend2C(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(descend2C(x, y));
    return rcpp_result_gen;
END_RCPP
}
// paretoFrontTest2C
List paretoFrontTest2C(arma::vec x, arma::vec y, arma::vec cluster_id, arma::uvec cluster_size, arma::vec x_null, arma::vec y_null, arma::uvec rsid_null);
RcppExport SEXP phantom_paretoFrontTest2C(SEXP xSEXP, SEXP ySEXP, SEXP cluster_idSEXP, SEXP cluster_sizeSEXP, SEXP x_nullSEXP, SEXP y_nullSEXP, SEXP rsid_nullSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type cluster_size(cluster_sizeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_null(x_nullSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_null(y_nullSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type rsid_null(rsid_nullSEXP);
    rcpp_result_gen = Rcpp::wrap(paretoFrontTest2C(x, y, cluster_id, cluster_size, x_null, y_null, rsid_null));
    return rcpp_result_gen;
END_RCPP
}
