# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getNullHetParamC <- function(DataList, GroupList, ncluster) {
    .Call(`_phantom_getNullHetParamC`, DataList, GroupList, ncluster)
}

cummaxC <- function(x) {
    .Call(`_phantom_cummaxC`, x)
}

descend2C <- function(x, y) {
    .Call(`_phantom_descend2C`, x, y)
}

paretoFrontTest2C <- function(x, y, cluster_id, cluster_size, x_null, y_null, rsid_null) {
    .Call(`_phantom_paretoFrontTest2C`, x, y, cluster_id, cluster_size, x_null, y_null, rsid_null)
}

